# Generated by Django 2.0.5 on 2018-05-04 18:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityTown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City / Town of', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='inspectionsEstablishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=100)),
                ('address', models.CharField(help_text='Enter address', max_length=200)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=16)),
                ('person_in_charge', models.CharField(help_text='Enter name of person in charge', max_length=100)),
                ('permit_no', models.CharField(help_text='Enter permit number', max_length=50)),
                ('city_town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.CityTown')),
            ],
        ),
        migrations.CreateModel(
            name='inspectionsEstablishmentInspectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Inspection Date')),
                ('inspection_data', models.CharField(help_text='Test data only', max_length=100, null=True)),
                ('inspections_establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.inspectionsEstablishment')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='Enter first name', max_length=50, verbose_name='First name')),
                ('lname', models.CharField(help_text='Enter last name', max_length=50, verbose_name='Last name')),
                ('status', models.CharField(choices=[('a', 'Active'), ('r', 'Retired')], default='a', help_text='Inspector status', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_operation', models.CharField(help_text='Enter operation', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='inspectionsestablishmentinspectionreport',
            name='inspector',
            field=models.ForeignKey(limit_choices_to={'status': 'a'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.Inspector'),
        ),
        migrations.AddField(
            model_name='inspectionsestablishment',
            name='type_of_operation',
            field=models.ManyToManyField(to='inspections.OperationType'),
        ),
    ]
